### ISSUE TITLE
Wrong handling of org.dom4j.tree.DefaultText nodes

### ISSUE THREAD

**Issue by mcarleio** [XenoAmess/remove-unused-imports-maven-plugin#20]
The generated pmd.xml may contain line breaks, which will be loaded as `org.dom4j.tree.DefaultText` nodes and therefor `haveOtherViolationsThatCannotAutoDelete` will be set to `true`, despite there aren't any further violations, just line breaks or text blocks.

**Comment by XenoAmess** [comment]
You are correct.
Will fix this bug in this week.
Thank you!!!
